version: "3.9"

services:

  mysql:
    image: mysql:8
    container_name: pmms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_mentor_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: pmms-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project_mentor_management
      DB_PORT: 3306
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend-service:5000
    image: pratikpatil1818/pmms-frontend



volumes:
  mysql_data:
